name: Update nginx

on:
  push:
    branches:
      - master
    paths:
      - "nginx/**"
      - ".github/workflows/nginx.yml"
  workflow_dispatch:

jobs:
  upload:
    name: Upload nginx config
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Upload nginx config"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ./nginx/7005.gutter
          target: /tmp/7005.gutter

  deploy:
    name: Restart nginx
    runs-on: self-hosted
    needs: upload
    steps:
      - name: "Move nginx to the right place"
        run: |
          sudo mv /tmp/7005.gutter/nginx/7005.gutter ${{ secrets.NGINX_DIST }}
          rm -rf /tmp/7005.gutter

      - name: "Replace vars in the file"
        run: |
          sed -i 's/SUBDOMAIN/${{ vars.SUBDOMAIN }}/g' ${{ secrets.NGINX_DIST }}
          sed -i 's/APP_PORT/${{ vars.APP_PORT }}/g' ${{ secrets.NGINX_DIST }}

      - name: "Restart nginx"
        run: |
          sudo systemctl restart nginx
